default: &default
  adapter: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  Host: ec2-3-93-206-109.compute-1.amazonaws.com
  Database: ddhmuiji4pisd4
  User: icxpmewscugtdw
  Password: 4ab6821d0642921a5eb3785d02825f66718f1834190232d2bfa7f79464adbb28

  

