puts "🌱 Seeding Literature..."

# Seed your database here
Book.create(title: "The Hunger Games", authors: "Suzanne Collins", image: "https://images.gr-assets.com/books/1447303603l/2767052.jpg", description: "Winning will make you famous. Losing means certain death.The nation of Panem, formed from a post-apocalyptic North America, is a country that consists of a wealthy Capitol region surrounded by 12 poorer districts. Early in its history, a rebellion led by a 13th district against the Capitol resulted in its destruction and the creation of an annual televised event known as the Hunger Games. In punishment, and as a reminder of the power and grace of the Capitol, each district must yield one boy and one girl between the ages of 12 and 18 through a lottery system to participate in the games. The 'tributes' are chosen during the annual Reaping and are forced to fight to the death, leaving only one survivor to claim victory.When 16-year-old Katniss's young sister, Prim, is selected as District 12's female representative, Katniss volunteers to take her place. She and her male counterpart Peeta, are pitted against bigger, stronger representatives, some of whom have trained for this their whole lives. , she sees it as a death sentence. But Katniss has been close to death before. For her, survival is second nature.", genre: "Young Adult, Fiction, Science Fiction, Dystopia, Fantasy, Science Fiction")
Book.create(title: "Harry Potter and the Order of the Phoenix", authors: "J.K. Rowling", image: "https://images.gr-assets.com/books/1255614970l/2.jpg", description: "There is a door at the end of a silent corridor. And it’s haunting Harry Pottter’s dreams. Why else would he be waking in the middle of the night, screaming in terror?Harry has a lot on his mind for this, his fifth year at Hogwarts: a Defense Against the Dark Arts teacher with a personality like poisoned honey; a big surprise on the Gryffindor Quidditch team; and the looming terror of the Ordinary Wizarding Level exams. But all these things pale next to the growing threat of He-Who-Must-Not-Be-Named---a threat that neither the magical government nor the authorities at Hogwarts can stop.As the grasp of darkness tightens, Harry must discover the true depth and strength of his friends, the importance of boundless loyalty, and the shocking price of unbearable sacrifice.His fate depends on them alll.(back cover)", genre: "Fantasy, Young Adult, Fiction")
Book.create(title: "To Kill a Mockingbird", authors: "Harper Lee", image: "https://images.gr-assets.com/books/1361975680l/2657.jpg", description: "The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it, To Kill A Mockingbird became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film, also a classic.Compassionate, dramatic, and deeply moving, To Kill A Mockingbird takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature.", genre: "Classics, Fiction, Historical, Historical Fiction, Academic, School")
Book.create(title: "Pride and Prejudice", authors: "Jane Austen", image: "https://images.gr-assets.com/books/1320399351l/1885.jpg", description: "Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language. Jane Austen called this brilliant work \"her own darling child\" and its vivacious heroine, Elizabeth Bennet, \"as delightful a creature as ever appeared in print.\" The romantic clash between the opinionated Elizabeth and her proud beau, Mr. Darcy, is a splendid performance of civilized sparring. And Jane Austen's radiant wit sparkles as her characters dance a delicate quadrille of flirtation and intrigue.", genre: "Classics, Fiction, Romance")
Book.create(title: "Twilight", authors: "Stephenie Meyer", image: "https://images.gr-assets.com/books/1361039443l/41865.jpg", description: "About three things I was absolutely positive.First, Edward was a vampire.Second, there was a part of him—and I didn't know how dominant that part might be—that thirsted for my blood.And third, I was unconditionally and irrevocably in love with him.In the first book of the Twilight Saga, internationally bestselling author Stephenie Meyer introduces Bella Swan and Edward Cullen, a pair of star-crossed lovers whose forbidden relationship ripens against the backdrop of small-town suspicion and a mysterious coven of vampires. This is a love story with bite.", genre: "Young Adult, Fantasy, Romance, Paranormal, Vampires, Fiction, Fantasy, Paranormal")
Book.create(title: "The Book Thief", authors: "Markus Zusak", image: "https://images.gr-assets.com/books/1522157426l/19063.jpg", description: "Trying to make sense of the horrors of World War II, Death relates the story of Liesel--a young German girl whose book-stealing and story-telling talents help sustain her family and the Jewish man they are hiding, as well as their neighbors.", genre: "Historical, Historical Fiction, Fiction, Young Adult")


puts "✅ Done seeding!"
